import SurahCard from "./SurahCard"

const SurahSidebar = () => {
	const surahs = [
		{ number: 1, name: "Fâtiha Suresi" },
		{ number: 2, name: "Bakara Suresi" },
		{ number: 3, name: "Âl-i İmran Suresi" },
		{ number: 4, name: "Nisâ Suresi" },
		{ number: 5, name: "Mâide Suresi" },
		{ number: 6, name: "En'âm Suresi" },
		{ number: 7, name: "A'râf Suresi" },
		{ number: 8, name: "Enfâl Suresi" },
		{ number: 9, name: "Tevbe Suresi" },
		{ number: 10, name: "Yûnus Suresi" },
		{ number: 11, name: "Hûd Suresi" },
		{ number: 12, name: "Yûsuf Suresi" },
		{ number: 13, name: "Ra'd Suresi" },
		{ number: 14, name: "İbrâhim Suresi" },
		{ number: 15, name: "Hicr Suresi" },
		{ number: 16, name: "Nahl Suresi" },
		{ number: 17, name: "İsrâ Suresi" },
		{ number: 18, name: "Kehf Suresi" },
		{ number: 19, name: "Meryem Suresi" },
		{ number: 20, name: "Tâ-Hâ Suresi" },
		{ number: 21, name: "Enbiyâ Suresi" },
		{ number: 22, name: "Hac Suresi" },
		{ number: 23, name: "Mü'minûn Suresi" },
		{ number: 24, name: "Nûr Suresi" },
		{ number: 25, name: "Furkân Suresi" },
		{ number: 26, name: "Şuarâ Suresi" },
		{ number: 27, name: "Neml Suresi" },
		{ number: 28, name: "Kasas Suresi" },
		{ number: 29, name: "Ankebût Suresi" },
		{ number: 30, name: "Rûm Suresi" },
		{ number: 31, name: "Lokmân Suresi" },
		{ number: 32, name: "Secde Suresi" },
		{ number: 33, name: "Ahzâb Suresi" },
		{ number: 34, name: "Sebe' Suresi" },
		{ number: 35, name: "Fâtır Suresi" },
		{ number: 36, name: "Yâsin Suresi" },
		{ number: 37, name: "Sâffât Suresi" },
		{ number: 38, name: "Sâd Suresi" },
		{ number: 39, name: "Zümer Suresi" },
		{ number: 40, name: "Mü'min Suresi" },
		{ number: 41, name: "Fussilet Suresi" },
		{ number: 42, name: "Şûrâ Suresi" },
		{ number: 43, name: "Zuhruf Suresi" },
		{ number: 44, name: "Duhân Suresi" },
		{ number: 45, name: "Câsiye Suresi" },
		{ number: 46, name: "Ahkâf Suresi" },
		{ number: 47, name: "Muhammed Suresi" },
		{ number: 48, name: "Fetih Suresi" },
		{ number: 49, name: "Hucurât Suresi" },
		{ number: 50, name: "Kâf Suresi" },
		{ number: 51, name: "Zâriyât Suresi" },
		{ number: 52, name: "Tûr Suresi" },
		{ number: 53, name: "Necm Suresi" },
		{ number: 54, name: "Kamer Suresi" },
		{ number: 55, name: "Rahmân Suresi" },
		{ number: 56, name: "Vâkıa Suresi" },
		{ number: 57, name: "Hadîd Suresi" },
		{ number: 58, name: "Mücâdele Suresi" },
		{ number: 59, name: "Haşr Suresi" },
		{ number: 60, name: "Mümtehine Suresi" },
		{ number: 61, name: "Saff Suresi" },
		{ number: 62, name: "Cum'a Suresi" },
		{ number: 63, name: "Münâfikûn Suresi" },
		{ number: 64, name: "Teğabün Suresi" },
		{ number: 65, name: "Talâk Suresi" },
		{ number: 66, name: "Tahrîm Suresi" },
		{ number: 67, name: "Mülk Suresi" },
		{ number: 68, name: "Kalem Suresi" },
		{ number: 69, name: "Hâkka Suresi" },
		{ number: 70, name: "Meâric Suresi" },
		{ number: 71, name: "Nûh Suresi" },
		{ number: 72, name: "Cin Suresi" },
		{ number: 73, name: "Müzzemmil Suresi" },
		{ number: 74, name: "Müddessir Suresi" },
		{ number: 75, name: "Kıyamet Suresi" },
		{ number: 76, name: "İnsan Suresi" },
		{ number: 77, name: "Mürselât Suresi" },
		{ number: 78, name: "Nebe' Suresi" },
		{ number: 79, name: "Nâziât Suresi" },
		{ number: 80, name: "Abese Suresi" },
		{ number: 81, name: "Tekvîr Suresi" },
		{ number: 82, name: "İnfitâr Suresi" },
		{ number: 83, name: "Mutaffifîn Suresi" },
		{ number: 84, name: "İnşikâk Suresi" },
		{ number: 85, name: "Bürûc Suresi" },
		{ number: 86, name: "Târık Suresi" },
		{ number: 87, name: "A'lâ Suresi" },
		{ number: 88, name: "Ğâşiye Suresi" },
		{ number: 89, name: "Fecr Suresi" },
		{ number: 90, name: "Beled Suresi" },
		{ number: 91, name: "Şems Suresi" },
		{ number: 92, name: "Leyl Suresi" },
		{ number: 93, name: "Duhâ Suresi" },
		{ number: 94, name: "İnşirâh Suresi" },
		{ number: 95, name: "Tîn Suresi" },
		{ number: 96, name: "Alak Suresi" },
		{ number: 97, name: "Kadir Suresi" },
		{ number: 98, name: "Beyyine Suresi" },
		{ number: 99, name: "Zilzâl Suresi" },
		{ number: 100, name: "Adiyât Suresi" },
		{ number: 101, name: "Kâria Suresi" },
		{ number: 102, name: "Tekâsür Suresi" },
		{ number: 103, name: "Asr Suresi" },
		{ number: 104, name: "Hümeze Suresi" },
		{ number: 105, name: "Fîl Suresi" },
		{ number: 106, name: "Kureyş Suresi" },
		{ number: 107, name: "Mâûn Suresi" },
		{ number: 108, name: "Kevser Suresi" },
		{ number: 109, name: "Kâfirûn Suresi" },
		{ number: 110, name: "Nasr Suresi" },
		{ number: 111, name: "Tebbet Suresi" },
		{ number: 112, name: "İhlâs Suresi" },
		{ number: 113, name: "Felâk Suresi" },
		{ number: 114, name: "Nâs Suresi" },
	]

	return (
		<div className="h-[90vh] w-[300px] flex flex-col relative ">
			<p className="p-4 text-lg font-semibold">SurahSidebar</p>
			<div className="flex-1 overflow-y-auto ">
				{surahs?.map((surah) => (
					<SurahCard key={surah.number} surah={surah} />
				))}
			</div>
			<div className="blur"></div>
		</div>
	)
}

export default SurahSidebar
