import SurahCard from "./SurahCard"

const SurahSidebar = ({ toggleSidebar }) => {
	const surahs = [
		{ number: 1, name: "Fâtiha", totalNumber: "7", originType: "Mekki" },
		{ number: 2, name: "Bakara", totalNumber: "286", originType: "Medeni" },
		{ number: 3, name: "Âl-i İmran", totalNumber: "200", originType: "Medeni" },
		{ number: 4, name: "Nisâ", totalNumber: "176", originType: "Medeni" },
		{ number: 5, name: "Mâide", totalNumber: "120", originType: "Medeni" },
		{ number: 6, name: "En'âm", totalNumber: "165", originType: "Mekki" },
		{ number: 7, name: "A'râf", totalNumber: "206", originType: "Mekki" },
		{ number: 8, name: "Enfâl", totalNumber: "75", originType: "Medeni" },
		{ number: 9, name: "Tevbe", totalNumber: "129", originType: "Medeni" },
		{ number: 10, name: "Yûnus", totalNumber: "109", originType: "Mekki" },
		{ number: 11, name: "Hûd", totalNumber: "123", originType: "Mekki" },
		{ number: 12, name: "Yûsuf", totalNumber: "111", originType: "Mekki" },
		{ number: 13, name: "Ra'd", totalNumber: "43", originType: "Medeni" },
		{ number: 14, name: "İbrâhim", totalNumber: "52", originType: "Mekki" },
		{ number: 15, name: "Hicr", totalNumber: "", originType: "" },
		{ number: 16, name: "Nahl", totalNumber: "", originType: "" },
		{ number: 17, name: "İsrâ", totalNumber: "", originType: "" },
		{ number: 18, name: "Kehf", totalNumber: "", originType: "" },
		{ number: 19, name: "Meryem", totalNumber: "", originType: "" },
		{ number: 20, name: "Tâ-Hâ", totalNumber: "", originType: "" },
		{ number: 21, name: "Enbiyâ", totalNumber: "", originType: "" },
		{ number: 22, name: "Hac", totalNumber: "", originType: "" },
		{ number: 23, name: "Mü'minûn", totalNumber: "", originType: "" },
		{ number: 24, name: "Nûr", totalNumber: "", originType: "" },
		{ number: 25, name: "Furkân", totalNumber: "", originType: "" },
		{ number: 26, name: "Şuarâ", totalNumber: "", originType: "" },
		{ number: 27, name: "Neml", totalNumber: "", originType: "" },
		{ number: 28, name: "Kasas", totalNumber: "", originType: "" },
		{ number: 29, name: "Ankebût", totalNumber: "", originType: "" },
		{ number: 30, name: "Rûm", totalNumber: "", originType: "" },
		{ number: 31, name: "Lokmân", totalNumber: "", originType: "" },
		{ number: 32, name: "Secde", totalNumber: "", originType: "" },
		{ number: 33, name: "Ahzâb", totalNumber: "", originType: "" },
		{ number: 34, name: "Sebe'", totalNumber: "", originType: "" },
		{ number: 35, name: "Fâtır", totalNumber: "", originType: "" },
		{ number: 36, name: "Yâsin", totalNumber: "", originType: "" },
		{ number: 37, name: "Sâffât", totalNumber: "", originType: "" },
		{ number: 38, name: "Sâd", totalNumber: "", originType: "" },
		{ number: 39, name: "Zümer", totalNumber: "", originType: "" },
		{ number: 40, name: "Mü'min", totalNumber: "", originType: "" },
		{ number: 41, name: "Fussilet", totalNumber: "", originType: "" },
		{ number: 42, name: "Şûrâ", totalNumber: "", originType: "" },
		{ number: 43, name: "Zuhruf", totalNumber: "", originType: "" },
		{ number: 44, name: "Duhân", totalNumber: "", originType: "" },
		{ number: 45, name: "Câsiye", totalNumber: "", originType: "" },
		{ number: 46, name: "Ahkâf", totalNumber: "", originType: "" },
		{ number: 47, name: "Muhammed", totalNumber: "", originType: "" },
		{ number: 48, name: "Fetih", totalNumber: "", originType: "" },
		{ number: 49, name: "Hucurât", totalNumber: "", originType: "" },
		{ number: 50, name: "Kâf", totalNumber: "", originType: "" },
		{ number: 51, name: "Zâriyât", totalNumber: "", originType: "" },
		{ number: 52, name: "Tûr", totalNumber: "", originType: "" },
		{ number: 53, name: "Necm", totalNumber: "", originType: "" },
		{ number: 54, name: "Kamer", totalNumber: "", originType: "" },
		{ number: 55, name: "Rahmân", totalNumber: "", originType: "" },
		{ number: 56, name: "Vâkıa", totalNumber: "", originType: "" },
		{ number: 57, name: "Hadîd", totalNumber: "", originType: "" },
		{ number: 58, name: "Mücâdele", totalNumber: "", originType: "" },
		{ number: 59, name: "Haşr", totalNumber: "", originType: "" },
		{ number: 60, name: "Mümtehine", totalNumber: "", originType: "" },
		{ number: 61, name: "Saff", totalNumber: "", originType: "" },
		{ number: 62, name: "Cum'a", totalNumber: "", originType: "" },
		{ number: 63, name: "Münâfikûn", totalNumber: "", originType: "" },
		{ number: 64, name: "Teğabün", totalNumber: "", originType: "" },
		{ number: 65, name: "Talâk", totalNumber: "", originType: "" },
		{ number: 66, name: "Tahrîm", totalNumber: "", originType: "" },
		{ number: 67, name: "Mülk", totalNumber: "", originType: "" },
		{ number: 68, name: "Kalem", totalNumber: "", originType: "" },
		{ number: 69, name: "Hâkka", totalNumber: "", originType: "" },
		{ number: 70, name: "Meâric", totalNumber: "", originType: "" },
		{ number: 71, name: "Nûh", totalNumber: "", originType: "" },
		{ number: 72, name: "Cin", totalNumber: "", originType: "" },
		{ number: 73, name: "Müzzemmil", totalNumber: "", originType: "" },
		{ number: 74, name: "Müddessir", totalNumber: "", originType: "" },
		{ number: 75, name: "Kıyamet", totalNumber: "", originType: "" },
		{ number: 76, name: "İnsan", totalNumber: "", originType: "" },
		{ number: 77, name: "Mürselât", totalNumber: "", originType: "" },
		{ number: 78, name: "Nebe'", totalNumber: "", originType: "" },
		{ number: 79, name: "Nâziât", totalNumber: "", originType: "" },
		{ number: 80, name: "Abese", totalNumber: "", originType: "" },
		{ number: 81, name: "Tekvîr", totalNumber: "", originType: "" },
		{ number: 82, name: "İnfitâr", totalNumber: "", originType: "" },
		{ number: 83, name: "Mutaffifîn", totalNumber: "", originType: "" },
		{ number: 84, name: "İnşikâk", totalNumber: "", originType: "" },
		{ number: 85, name: "Bürûc", totalNumber: "", originType: "" },
		{ number: 86, name: "Târık", totalNumber: "", originType: "" },
		{ number: 87, name: "A'lâ", totalNumber: "", originType: "" },
		{ number: 88, name: "Ğâşiye", totalNumber: "", originType: "" },
		{ number: 89, name: "Fecr", totalNumber: "", originType: "" },
		{ number: 90, name: "Beled", totalNumber: "", originType: "" },
		{ number: 91, name: "Şems", totalNumber: "", originType: "" },
		{ number: 92, name: "Leyl", totalNumber: "", originType: "" },
		{ number: 93, name: "Duhâ", totalNumber: "", originType: "" },
		{ number: 94, name: "İnşirâh", totalNumber: "", originType: "" },
		{ number: 95, name: "Tîn", totalNumber: "", originType: "" },
		{ number: 96, name: "Alak", totalNumber: "", originType: "" },
		{ number: 97, name: "Kadir", totalNumber: "", originType: "" },
		{ number: 98, name: "Beyyine", totalNumber: "", originType: "" },
		{ number: 99, name: "Zilzâl", totalNumber: "", originType: "" },
		{ number: 100, name: "Adiyât", totalNumber: "", originType: "" },
		{ number: 101, name: "Kâria", totalNumber: "", originType: "" },
		{ number: 102, name: "Tekâsür", totalNumber: "", originType: "" },
		{ number: 103, name: "Asr", totalNumber: "", originType: "" },
		{ number: 104, name: "Hümeze", totalNumber: "", originType: "" },
		{ number: 105, name: "Fîl", totalNumber: "", originType: "" },
		{ number: 106, name: "Kureyş", totalNumber: "", originType: "" },
		{ number: 107, name: "Mâûn", totalNumber: "", originType: "" },
		{ number: 108, name: "Kevser", totalNumber: "", originType: "" },
		{ number: 109, name: "Kâfirûn", totalNumber: "", originType: "" },
		{ number: 110, name: "Nasr", totalNumber: "", originType: "" },
		{ number: 111, name: "Tebbet", totalNumber: "", originType: "" },
		{ number: 112, name: "İhlâs", totalNumber: "", originType: "" },
		{ number: 113, name: "Felâk", totalNumber: "", originType: "" },
		{ number: 114, name: "Nâs", totalNumber: "", originType: "" },
	]

	return (
		<div className="h-[100vh] w-[330px] flex flex-col relative ">
			<p className="font-bold text-center text-[#616b76]">TÜM SURE OKU</p>
			<div className="flex-1 overflow-y-auto ">
				{surahs?.map((surah) => (
					<SurahCard key={surah.number} surah={surah} toggleSidebar={toggleSidebar} />
				))}
			</div>
			<div className="blur"></div>
		</div>
	)
}

export default SurahSidebar
