import "./globals.css"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html>
			<body className=" vsc-initialized">{children}</body>
		</html>
	)
}
