import "./globals.css"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html>
			<body className="vsc-initialized">
				<div className="header-container">
					<h1 className="header-text">
						كِتَابٌ أَنزَلْنَاهُ إِلَيْكَ مُبَارَكٌ لِّيَدَّبَّرُوا آيَاتِهِ وَلِيَتَذَكَّرَ أُولُو الْأَلْبَابِ
					</h1>
				</div>
				{children}
			</body>
		</html>
	)
}
